util/src/main/java/com/psddev/dari/util/DimsImageEditor.java
Where if the imageUrl is already a dims url it may return a different base url than what is already present.
=> Fixes issue with multiple base urls.

db/etc/clirr-ignored.xml, db/src/main/java/com/psddev/dari/db/AggregateDatabase.java, db/src/main/java/com/psddev/dari/db/Database.java, db/src/main/java/com/psddev/dari/db/DistributedLock.java, db/src/main/java/com/psddev/dari/db/ForwardingDatabase.java, db/src/main/java/com/psddev/dari/db/SqlDatabase.java
SqlDatabase#now already exists.
=> Adds Database#now and modifies DistributedLock to use it.

db/src/main/java/com/psddev/dari/db/ValidationException.java
adds null check on embeddedStateField
=> adds null check on embeddedStateField

util/src/main/java/com/psddev/dari/util/HtmlGrid.java
Add hook to HtmlGrid to allow specification of grid css file paths
=> Add hook to restrict the paths to search for grid styles

db/src/main/java/com/psddev/dari/db/Application.java
Fixes Application to set name on save if none provided to avoid validation exception due to singleton.
=> Application Singleton

util/src/main/java/com/psddev/dari/util/CodeDebugServlet.java
Fix NPE when subdir of  WEB_INF_CLASSES_PATH is empty
=> Fix NPE when subdir is empty.

util/src/main/java/com/psddev/dari/util/TypeDefinition.java, util/src/test/java/com/psddev/dari/util/TypeDefinitionTest.java
=> Revert "TypeDefinition#getAllMethods default interface method support"

twilio/src/main/java/com/psddev/dari/util/TwilioSmsProvider.java
=> Upgrades Twilio API

db/src/main/java/com/psddev/dari/db/RecalculationTask.java
=> Add task host setting to RecalculationTask.

db/src/main/java/com/psddev/dari/db/SqlQuery.java
Given a query like Query.from(Article.class).where("section = ?",
sections), the generated SQL query looked like section = id1 OR section
= id2.
This optimization rewrites that to section IN (id1, id2) which is
faster in MySQL.
BSP-1643
=> Performance optimization by using IN instead of OR.

db/src/main/java/com/psddev/dari/db/SqlDatabase.java
These allow the JNDI datasource to be somewhere other than dari/database
=> Add dataSourceJndiName and readDataSourceJndiName settings

grandparent/pom.xml, util/src/main/java/com/psddev/dari/util/CodeUtils.java
=> Adds default maven generated sources directory to CodeUtils watch list.

db/src/main/java/com/psddev/dari/db/AsyncStorageItemWriter.java, db/src/main/java/com/psddev/dari/db/StorageDebugServlet.java
=> Fixes StorageDebugServlet sometimes skipping items and improves performance.

util/src/main/java/com/psddev/dari/util/ClassFinder.java
This only affects ClassFinder's ServletContext fallback behavior.
=> Check file names (as Strings) when adding class names to list of classes

db/src/main/java/com/psddev/dari/db/ReferentialText.java
=> Revert "Changes ref text to lazily load references."

db/src/main/java/com/psddev/dari/db/ReferentialText.java
=> Revert "Revert "Changes ref text to lazily load references.""

db/src/main/java/com/psddev/dari/db/BulkDebugServlet.java
=> BSP-1300 Add ability to adjust writerCount/commitSize on DB Bulk Copy Servlet

pom.xml
See release notes for Jsoup 1.9.1 https://jsoup.org/news/release-1.9.1
=> BSP-2058 Upgrades Jsoup from 1.8.3 to 1.9.1 to pick up bug fixes and performance improvements.

db/src/main/java/com/psddev/dari/db/MySQLBinaryLogEventListener.java
Example output:
```
16-Sep-2016 14:27:00 DEBUG [Thread-5] com.psddev.dari.db.MySQLBinaryLogEventListener Event: timestamp=[1474050420000], lag=[535], type=[EXT_WRITE_ROWS], dataLength=[317]
16-Sep-2016 14:27:00 DEBUG [Thread-5] com.psddev.dari.db.MySQLBinaryLogEventListener Event: timestamp=[1474050420000], lag=[547], type=[EXT_UPDATE_ROWS], dataLength=[447]
16-Sep-2016 14:27:00 DEBUG [Thread-5] com.psddev.dari.db.MySQLBinaryLogEventListener Cache update: typeId=[000001571006d77ca97fd9872031], id=[000001571006d77ca97fd98738710000]
16-Sep-2016 14:27:00 DEBUG [Thread-5] com.psddev.dari.db.MySQLBinaryLogEventListener Event: timestamp=[1474050420000], lag=[552], type=[EXT_DELETE_ROWS], dataLength=[317]
16-Sep-2016 14:27:00 DEBUG [Thread-5] com.psddev.dari.db.MySQLBinaryLogEventListener Cache …
```
=> BSP-2557: Improves replication cache logging.

util/src/main/java/com/psddev/dari/util/ClassFinder.java
Performance numbers on each optimization. The times are in milliseconds.
Before:
com.psddev.dari.util.ClassEnhancer: 757.720534
com.psddev.dari.db.Recordable: 1603.538312
com.psddev.analytics.AnalyticsRange: 1159.056441
com.psddev.dari.util.sa.JvmAnalyzer: 827.61531
com.psddev.dari.util.AbstractFilter$Auto: 791.736512
com.psddev.community.AbstractSearchPage: 908.541306
com.psddev.cms.rte.RichTextToolbar: 971.126775
com.psddev.cms.db.RichTextElement: 834.312864
com.psddev.cms.tool.ToolPageHead: 801.874021
com.psddev.cms.tool.Tab: 845.624254
com.psddev.cms.rtc.RtcBroadcast: 1146.156512
After JAR optimization:
com.psddev.dari.util.ClassEnhancer: 590.510955
com.psddev.dari.db.Recordable: 575.31487
com.psddev.analytics.AnalyticsRange: 593.044591
com.psddev.dari.util.sa.JvmAnalyzer: 576.897778 …
=> BSP-2675: Improve class finder performance

util/src/main/java/com/psddev/dari/util/JavaImageServlet.java
=> BSP-2949 Fixes mime content type for JPEGs

db/src/main/java/com/psddev/dari/db/Query.java
=> Adds javadocs to Query methods

db/src/main/java/com/psddev/dari/db/QueryPhrase.java, db/src/main/java/com/psddev/dari/db/QueryPhraseBuilder.java, db/src/main/java/com/psddev/dari/db/SolrDatabase.java, db/src/main/java/com/psddev/dari/db/SqlQuery.java, sql/src/main/java/com/psddev/dari/sql/SqlQuery.java
Usage:
```java
Query.from(Article.class)
.where("_any matches ?", QueryPhrase.builder()
.phrase("hello world")
.proximity(2) // how far apart can the words in this phrase be?
.weight(10.0) // how important is this phrase?
.build()) // equivalent to (_any:"hello world"~2^10.0) in Solr
.select(0, 10);
```
=> Adds query phrase support.

db/src/main/java/com/psddev/dari/db/ObjectType.java
https://perfectsense.atlassian.net/browse/BSP-3323
=> BSP-3323: updates ObjectType::isConcrete to be Indexed
