perfectsense/dari

db/src/main/java/com/psddev/dari/db/ObjectIndex.java
ObjectIndex#getValue and ObjectIndex#getValuePermutations were using
State#get, they should be using State#getByPath.
=> Fixes bug in support for unique indexes on ObjectMethods.

db/src/main/java/com/psddev/dari/db/SqlDatabase.java
Avoids producing objects in SqlDatabase/findObjectsFromReplicationCache when the objects’ type does not match the requested Query/objectClass and Query/group.
=> BSP-878 Fixes bug where replicationCache produces objects by ID for incompatible types.

util/src/main/java/com/psddev/dari/util/RepeatingTask.java
Updates RepeatingTask/every to add offset using DateTime.withFieldAdded API to prevent out of bounds units from being set on a DateTime.
=> Updates RepeatingTask/every to add offset using DateTime.withFieldAdded

db/src/main/java/com/psddev/dari/db/Application.java
Deprecates Application.initialize, as it is only invoked from a @Deprecated class.  Any @Overriding implementations in derived classes are not invoked during normal Application functionality.
=> Deprecates Application.initialize, as it is only invoked from a @Deprecated class.

db/src/main/java/com/psddev/dari/db/Query.java, db/src/main/java/com/psddev/dari/db/SqlDatabase.java
Changes sqlQueryCache to not use weakKeys() and fixes Query#equals() and
hashCode() to include fields, as getFields() is used to build the query.
=> Fixes bug in sqlQueryCache Query equivalence.

db/src/main/java/com/psddev/dari/db/BulkDebugServlet.java
This prevents the SQL query from being killed if it runs longer than
the removeAbandonedTimeout.
=> Add USE_JDBC_FETCH_SIZE_QUERY_OPTION=false to all bulk queries.

util/src/main/java/com/psddev/dari/util/DimsImageEditor.java, util/src/main/java/com/psddev/dari/util/StorageItemPathHash.java
Uses MD5 hash so that it is more random and therefore more evenly distributed after the modulus is applied to the result.
=> Improves the hash algorithm for calculating the baseUrl

util/src/main/java/com/psddev/dari/util/JavaImageEditor.java
Always creates a new Map and copies the relevant metadata over.  Fixes issue where subsequent edits to the same image could result in incorrect crops. This is now consistent with DimsImageEditor.
=> Fixes JavaImageEditor modifying the existing image's metadata map.

db/src/main/java/com/psddev/dari/db/ObjectMethod.java
Moves the "has single object method" cached value from a transient field
on the ObjectMethod object to an extra in the ObjectMethod's state to
prevent getting the wrong value when the object is reused.
=> Fix "wrong number of arguments" exception.

util/src/main/java/com/psddev/dari/util/TypeDefinition.java, util/src/test/java/com/psddev/dari/util/TypeDefinitionTest.java
Gets the inferred generic type argument class of the type definition instance type for a given super class (or interface) and its generic type argument index.
=> Adds method TypeDefinition#getInferredGenericTypeArgumentClass.

util/src/main/java/com/psddev/dari/util/TypeDefinition.java, util/src/test/java/com/psddev/dari/util/TypeDefinitionTest.java
Improves TypeDefinition#getAllMethods to include default interface methods introduced in Java 8.
=> TypeDefinition#getAllMethods default interface method support

image/src/main/java/com/psddev/dari/util/ImageMetadataMap.java, pom.xml
Updating this plugin provides improved metadata extraction results.
Here is a comparison of the old vs. new version using the same image.
**v.2.4.0-beta-1**
```
"metadata" : {
"originalFilename" : "forest-road.jpg",
"http.headers" : {
"Cache-Control" : [ "public, max-age=31536000" ],
"Content-Length" : [ "2461109" ],
"Content-Type" : [ "image/jpeg" ]
},
"Exif" : {
"Compression" : "JPEG (old-style)",
"Exif Version" : "2.21",
"Date/Time" : "2015:10:26 13:12:59",
"Thumbnail Image Width" : "2100 pixels",
"Samples Per Pixel" : "3 samples/pixel",
"Exif Image Width" : "2100 pixels",
"Orientation" : "Top, left side (Horizontal / normal)",
"X Resolution" : "72 dots per inch",
"Photometric Interpretation" : "RGB",
"Resolution Unit" : "Inch",
"Thumbnail Length" : "10526 bytes",
"Color Space" : …
```
=> Update Metadata Extractor dependency

db/etc/clirr-ignored.xml, db/src/main/java/com/psddev/dari/db/RecalculationDelay.java, db/src/main/java/com/psddev/dari/db/RecalculationTask.java
This calculates the minimum Metric event date used to find the list of
records whose metric values have changed and need to be recalculated. Using
the last processed date as-is is subtly wrong in two scenarios:
1. If the metric value hasn't incremented at all since the last
recalculation date, recalculation will skip it and the indexed value
will always reflect the value of the last recalculation
2. If the metric values arrive on a delay, such as with third party
analytics providers.
=> Add RecalculationDelay#metricAfterDate.

util/src/main/java/com/psddev/dari/util/StringUtils.java, util/src/test/java/com/psddev/dari/util/StringUtilsTest.java
Happened when the input string had leading word delimiter characters.
=> Fixes StringIndexOutOfBoundsException in StringUtils#toPascalCase.

util/src/main/java/com/psddev/dari/util/SourceFilter.java
The reloader download does not follow redirects and was getting a 301
redirect after the repo moved.
=> Fix reloader installation

db/src/main/java/com/psddev/dari/db/AsyncStorageItemWriter.java, db/src/main/java/com/psddev/dari/db/StorageDebugServlet.java, image/src/main/java/com/psddev/dari/util/ImageResizeStorageItemListener.java, storage/src/main/java/com/psddev/dari/util/AbstractStorageItem.java, storage/src/main/java/com/psddev/dari/util/StorageItem.java
Fixes saveObject checkbox not getting processed on form submission in the StorageDebugServlet. The saveObject checkbox did not have a value set, and browsers like chrome default the value to "on" instead of the expected value of "true".
Fixes State map not getting properly updated when copying StorageItems. This is a workaround for a different bug with the State#entrySet / State.Entry#setValue API where calling setValue does not properly update the State and a subsequent call to State#save would lose any changes made. The workaround is to loop over the State#keySet and just call State#put directly.
Fixes metadata not getting copied in StorageItem.Static#copy API. This originated from the StorageItem.Static#copy API not getting updated when the concept of StorageItem metadata was later …
=> BSP-1586; Fixes several issues preventing StorageDebugServlet from copying files properly.

db/src/main/java/com/psddev/dari/db/SqlQuery.java
See: da721bd. If any predicate limits the resultset, it is more
efficient to meet those conditions before pulling in the typeId. If all
of the predicates are NOT IN or != or IS NOT NULL, the resultset is
still effectively unlimited, and the PRIMARY key is the optimal
execution plan.
=> Changes SqlQuery to skip the IGNORE INDEX (PRIMARY) hint when appropriate.

db/src/main/java/com/psddev/dari/db/SqlDatabase.java
Brightspot fails to start as mastercard are using an enterprise version of Postgres.
This PR fixes the issue (Thx Lee) by adding an entry for "EnterpriseDB" to the map.
=> added EnterpriseDB to sql vendor class map

image/src/main/java/com/psddev/dari/util/JavaImageEditor.java, storage/src/main/java/com/psddev/dari/util/LocalStorageItem.java
This PR also updates JavaImageEditor to use originBaseUrl when it's available.
=> BSP-2071: Add ability to set originBaseUrl for LocalStorageItem

image/src/main/java/com/psddev/dari/util/JavaImageServlet.java
OpenJDK 8 fails with the error "javax.imageio.IIOException: Invalid
argument to native writeImage" when an PNG with transparency is
resized. This appears to be because it tries to generate a JPG with
transparency for the hash value which is not supported in OpenJDK 8.
=> Fix Java Image Editor bug when used with OpenJDK 8

parent/pom.xml
Caused failed builds on Windows file systems.
=> Fixes groovy script to use scoped variable instead of string interpolation.

util/src/main/java/com/psddev/dari/util/CodeUtils.java
When executing code in the `_debug/code` tool, the method being executed is very random if there's more than one static method with no parameters (even if only one of them is public!).
This PR tries first to execute a method named `main`, otherwise a random one is executed (as before).
=> Debug Code Editor: Try to execute a method named main first

image/src/main/java/com/psddev/dari/util/DimsImageEditor.java
Not when modifying an existing DIMS url. Only the image path needs to be validated as a wellformed URL (file or http).
This also reverts https://github.com/perfectsense/dari/pull/200
=> BSP-2272: Only prepend "file:" to the URL in context of a new image edit request.

grandparent/pom.xml
https://issues.apache.org/jira/browse/MPIR-234
=> BSP-1678: Hack to remove artifactId in SCM URLs.

db/src/main/java/com/psddev/dari/db/ColorImage.java
Prevents excessive calls by upstream processes.
=> BSP-2438 Changes ColorImageData#beforeSave to beforeCommit

db/pom.xml
This is mainly to pick up
https://github.com/shyiko/mysql-binlog-connector-java/commit/7efa961867b
55284bb9bf7932f63a4536fe55da3 fix.
=> BSP-1212: Upgrades shyiko mysql replication library to 0.4.2.

db/src/main/java/com/psddev/dari/db/LazyLoadEnhancer.java, db/src/main/java/com/psddev/dari/db/State.java, h2/pom.xml, h2/src/test/java/com/psddev/dari/h2/StateTest.java
BSP-2801 changes location of expression to set ALL_RESOLVED_FLAG so that a second Thread executing State#resolveReference will be forced to wait at the synchronized block until the first Thread has completed resolving references.
=> BSP-2801 Makes State#resolveReference Thread-safe

db/src/main/java/com/psddev/dari/db/DistributedLock.java
Since the key is an adhoc type-less object, this ensures that any global modification triggers aren't fired potentially causing unintended mutations to the key's state.
=> BSP-3290: Changes the save of DistributedLock key to skip validation and triggers.

db/src/main/java/com/psddev/dari/db/QueryPhrase.java, db/src/main/java/com/psddev/dari/db/QueryPhraseBuilder.java, db/src/main/java/com/psddev/dari/db/SolrDatabase.java, db/src/main/java/com/psddev/dari/db/SqlQuery.java, sql/src/main/java/com/psddev/dari/sql/SqlQuery.java
Usage:
```java
Query.from(Article.class)
.where("_any matches ?", QueryPhrase.builder()
.phrase("hello world")
.proximity(2) // how far apart can the words in this phrase be?
.weight(10.0) // how important is this phrase?
.build()) // equivalent to (_any:"hello world"~2^10.0) in Solr
.select(0, 10);
```
=> BSP-3578: Adds query phrase support.
